version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    volumes:
      - .:/rails
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      RAILS_ENV: ${RAILS_ENV:-development}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  postgres_data:
